config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'users/new', as: 'new_user_registration'

  get 'users/create', as: 'create_new_user'

  get 'questionnaire_select/:id', to: 'questions#questionnaire_select', as: 'questionnaire_select'

  patch '/questions/:id/update_questionnaire', to: 'questions#update_questionnaire', as: 'update_questionnaire'

  delete '/questionnaires/:questionnaire_id/questions/:id', to: 'questions#destroy', as: 'destroy_question'

  post '/results/create', to: 'results#create', as: 'create_result'

  get '/questionnaires/:questionnaire_id/category/:id/show', to: 'category#show', as: 'display_category'

  patch '/questionnaires/:questionnaire_id/category/:id', to: 'category#record', as: 'record_category'

  get '/questionnaires/:questionnaire_id/results/:id/display', to: 'results#display', as: "questionnaire_result"

  get '/questionnaires/:questionnaire_id/results/:id', to: 'results#show', as: "result"

  get '/questionnaires/:questionnaire_id/category/:id/category_data', to: 'category#category_data', as: "category_data"

  resources :users

  resources :questionnaires do
    resources :questions, except: [:destroy]
    resources :results, except: [:create, :show]
  end
  post 'sessions/create_manual', as: 'create_user_session'

  get 'signout', to: 'sessions#destroy', as: 'signout'

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionnaire
  belongs_to :user
  belongs_to :category

  validates :body, presence: true
  validates :category_id, presence: true


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_login
  def index
    @questions = Question.where("(questionnaire_id = #{params[:questionnaire_id]})")
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  def new
    @question = Question.new
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  def create
    @question = Question.new
    @question.body = params[:question][:body]
    @question.category = Category.find(params[:question][:category_id])
    @question.questionnaire = Questionnaire.find(params[:questionnaire_id])
    if @question.save
      redirect_to questionnaire_path(params[:questionnaire_id])
    else
      session[:errors] = @question.errors.full_messages
      redirect_to new_questionnaire_question_path(@question.questionnaire)
    end
  end

  def edit
    @question = Question.find(params[:id])
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  def update
    @question = Question.find(params[:id])
    @question.body = params[:question][:body]
    @question.category = Category.find(params[:question][:category_id])
    @question.questionnaire = Questionnaire.find(params[:questionnaire_id])
    if @question.save
      redirect_to questionnaire_path(params[:questionnaire_id])
    else
      session[:errors] = @question.errors.full_messages
      redirect_to edit_questionnaire_question_path(@question.questionnaire, @question)
    end
  end


  def show
    @question = Question.find(params[:id])
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  def destroy
    @question = Question.find(params[:id])
    @questionnaire = @question.questionnaire
    @question.delete
    redirect_to questionnaire_path(@questionnaire.id)
  end


  def update_questionnaire
    @questionnaire = Questionnaire.find(params[:question][:questionnaire_id])
    @question = Question.find(params[:id])
    @question.questionnaire = @questionnaire

    redirect_to questionnaire_questions_path(@questionnaire.id)
  end

  private
  def question_params
    params.require(:question).permit(:body, :category_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for([@questionnaire, Question.create]) do |f| %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %><hr>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_form_edit.html.erb
<%= form_for([@questionnaire, @question]) do |f| %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %><hr>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form_edit' %>

<%= link_to 'Back', root_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<%= link_to 'Add New Question', new_questionnaire_question_path(@questionnaire), class: "btn btn-info" %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.reverse_each do |question| %>
      <div class="question_content">
        <% if question.questionnaire %>
          <!-- true -->
          <tr>
            <td>In the past 7 days, I <%= question.body %></td>
            <td>Category: <%= question.category.name %></td>
            <td class="btn btn-outline-info btn-lg active"><%= link_to 'Show', questionnaire_question_path(question.questionnaire.id, question.id) %></td>
            <% if question.questionnaire.id != 1 %>
              <td class="btn btn-outline-info btn-lg active"><%= link_to 'Edit', edit_questionnaire_question_path(question.questionnaire.id, question.id) %></td>
              <td class="btn btn-outline-info btn-lg active"><%= link_to 'Destroy', destroy_question_path(question.questionnaire, question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>

          </tr>
        <% else %>
          <tr>
            <td class="add_question_to_questionnaire">Body: <%= question.body %></td>
            <td class="add_question_to_questionnaire">Category: <%= question.category %></td>
            <td class="add_question_to_questionnaire btn btn-outline-info"><%= link_to "Add this question to a questionnaire", questionnaire_select_path(question) %></td>
        <% end %>
      </tr>
      <% end %>
    </div>
  </tbody>
</table>

<br>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaire_path(@questionnaire) %>

app/views/questions/questionnaire_select.html.erb
<% if Questionnaire.my_questionnaires(current_user.id).count > 0  %>
  <h4>Select a Questionnaire to add <span style="color:green;"> <%= @question.body %></span> to</h4>
<% else %>
  <h4>You have not created any custom questionnaires.</h4>
  <h4><%= link_to "Create a questionnaire", new_questionnaire_path %></h4>
  <%= link_to "Or return to the question list", questionnaire_questions_path(Questionnaire.first) %>
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>This question: </strong>belongs to the <strong><%= @question.category %></strong> category</p>
<p>and the <strong><%= @questionnaire.name %></strong> questionnaire</p> 

<%= link_to 'Edit', edit_questionnaire_question_path(@questionnaire, @question) %> |
<%= link_to 'Back', questionnaire_questions_path(@questionnaire) %>