config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'users/new', as: 'new_user_registration'

  get 'users/create', as: 'create_new_user'

  get 'questionnaire_select/:id', to: 'questions#questionnaire_select', as: 'questionnaire_select'

  patch '/questions/:id/update_questionnaire', to: 'questions#update_questionnaire', as: 'update_questionnaire'

  delete '/questionnaires/:questionnaire_id/questions/:id', to: 'questions#destroy', as: 'destroy_question'

  post '/results/create', to: 'results#create', as: 'create_result'

  get '/questionnaires/:questionnaire_id/category/:id/show', to: 'category#show', as: 'display_category'

  patch '/questionnaires/:questionnaire_id/category/:id', to: 'category#record', as: 'record_category'

  get '/questionnaires/:questionnaire_id/results/:id/display', to: 'results#display', as: "questionnaire_result"

  get '/questionnaires/:questionnaire_id/results/:id', to: 'results#show', as: "result"

  get '/questionnaires/:questionnaire_id/category/:id/category_data', to: 'category#category_data', as: "category_data"

  resources :users

  resources :questionnaires do
    resources :questions, except: [:destroy]
    resources :results, except: [:create, :show]
  end
  post 'sessions/create_manual', as: 'create_user_session'

  get 'signout', to: 'sessions#destroy', as: 'signout'

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @result = Result.new
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h2>Welcome to the Quality of Life Tool</h2>
<% if !user_signed_in? %>
  <%= link_to "Log in", '/login' %> <hr>
  <%= link_to "or Sign up", new_user_registration_path %><hr>
  <%= link_to 'Login with Facebook', '/auth/facebook' %>
<% else %>
  <strong>Welcome, <%= current_user.name %></strong> <hr>
  <%= form_for @result, :url => create_result_path do |f| %>
    <%= f.label "Choose a questionnaire (Quality of Life Recommmended)" %><br>
    <%= f.collection_select :questionnaire_id, Questionnaire.all_questionnaires(current_user.id), :id, :name, {:prompt => 'Choose a questionnaire'}, {:required => true} %>
    <%= f.submit "Take Questionnaire" %>
  <% end %>
  <hr>
  <%= link_to "All my Questionnaires", questionnaires_path, id: "questionnaire-index" %> <hr>
  <%= link_to "Create a New Questionnaire", new_questionnaire_path %> <hr>
  <%= link_to "See my Past Results", questionnaire_results_path(Questionnaire.last) %> <hr>
  <div id="questionnaires-list" data-current-user-id="<%= current_user.id %>">

  </div>

<% end %>

<script type="text/javascript">
  $("#questionnaire-index").on('click', function(event) {
    event.preventDefault();

    $.ajax({
      url: '/questionnaires',
      type: 'GET'
    }).done(function(questionnaires) {
      $("#questionnaires-list").append(`<h2>Questionnaires List</h2>`)
      questionnaires
        .sort((a, b) => {
          var nameA = a.name.toUpperCase()
          var nameB = b.name.toUpperCase()
          if (nameA > nameB) {
            return 1;
          }
          if (nameA < nameB) {
            return -1
          }
          return 0;
        })
        .forEach(question => {
          debugger;
          $("#questionnaires-list").append(`
            <p>${question.name}</p>
            <p>User: ${question.user.name}</p>
            <a href="/questionnaires/${question.id}/edit">Edit</a> | <a href="/questionnaires/${question.id}">Go to Questions</a>
            <hr />
          `)
        })
    })
  })
</script>