config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'users/new', as: 'new_user_registration'

  get 'users/create', as: 'create_new_user'

  get 'questionnaire_select/:id', to: 'questions#questionnaire_select', as: 'questionnaire_select'

  patch '/questions/:id/update_questionnaire', to: 'questions#update_questionnaire', as: 'update_questionnaire'

  delete '/questionnaires/:questionnaire_id/questions/:id', to: 'questions#destroy', as: 'destroy_question'

  post '/results/create', to: 'results#create', as: 'create_result'

  get '/questionnaires/:questionnaire_id/category/:id/show', to: 'category#show', as: 'display_category'

  patch '/questionnaires/:questionnaire_id/category/:id', to: 'category#record', as: 'record_category'

  get '/questionnaires/:questionnaire_id/results/:id/display', to: 'results#display', as: "questionnaire_result"

  get '/questionnaires/:questionnaire_id/results/:id', to: 'results#show', as: "result"

  get '/questionnaires/:questionnaire_id/category/:id/category_data', to: 'category#category_data', as: "category_data"

  resources :users

  resources :questionnaires do
    resources :questions, except: [:destroy]
    resources :results, except: [:create, :show]
  end
  post 'sessions/create_manual', as: 'create_user_session'

  get 'signout', to: 'sessions#destroy', as: 'signout'

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :questionnaire
  has_many :category_ratings
  belongs_to :user
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :require_login
  def create
    @questionnaire = Questionnaire.find(params[:result][:questionnaire_id])
    @result = Result.new
    @result.name = @questionnaire.name
    @result.questionnaire = @questionnaire
    @result.user = current_user
    @result.rating = 0
    if @result.save
      session[:result_id] = @result.id
      redirect_to display_category_path(@questionnaire, Category.first)
    else
      flash[:error] = "Invalid result"
      redirect_to root_path
    end
  end

  def display
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
    @result = Result.find(params[:id])
    @categories = Category.all
    @category_ratings = @result.category_ratings
    @category_ratings.each do |category_rating|
      @result.category_ratings << category_rating
      @result.rating += category_rating.rating
    end
    @result.save
  end

  def index
    @results = Result.where("user_id = #{current_user.id}")
  end

  def show
    @result = Result.find(params[:id])
    @categories = Category.all
    render json: @result 
  end


end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/display.html.erb
<h2>Results of the <%= @questionnaire.name %> Questionnaire</h2>
From 4 to 20, your <%= @questionnaire.name %> results are:
<hr>
<div id="result-hook"></div>
Total: <%= @result.rating %> <hr>
<%= link_to "Results index", questionnaire_results_path(@questionnaire) %>
<script type="text/javascript">
  $(function() {
    function CategoryRating(categoryName, rating) {
      this.categoryName = categoryName;
      this.rating = rating;
      this.toPage = function() {
        return `<h4>${categoryName}</h4><br /><p>Rating: <strong>${rating}</strong></p><hr />`
      }
    }

    $.get('/questionnaires/<%= @questionnaire.id %>/results/<%= Result.find(session[:result_id]).id %>', function(data) {
      for (var i = 0, l = data["category_ratings"].length; i < l; i++) {
        var category_name = data["category_ratings"][i]["category"]["name"]
        var rating = data["category_ratings"][i]["rating"]
        var category_rating = new CategoryRating(category_name, rating);
        // debugger
        $(`#result-hook`).append(category_rating.toPage())
      }
    })
  })


</script>

app/views/results/index.html.erb
<h1>Your Results</h1>
<tbody>
  <% @results.reverse_each do |result| %>
    <tr>
        <td><h3><%= result.questionnaire.name %></h3></td><br>
        <td>Total Score: <%= result.rating %></td><br>
        <td><%= link_to "See Category Ratings", result_path(result.questionnaire, result), class: "category_rating" %></td>
        <div id="result-hook-<%= result.id %>"></div>
    </tr>
    <hr>

  <% end %>
</tbody>

<script type="text/javascript">
  function CategoryRating(categoryName, rating) {
    this.categoryName = categoryName;
    this.rating = rating;
    this.toPage = function() {
      return `<h4>${categoryName}</h4><br /><p>Rating: <strong>${rating}</strong></p><hr />`
    }
  }
  for (var e = 0, m = $('a.category_rating').length; e < m; e++) {
    $('a.category_rating').eq(e).on('click', function(event) {
      event.preventDefault()
      $.get(this.href, function(data) {
        for (var i = 0, l = data["category_ratings"].length; i < l; i++) {
          var category_name = data["category_ratings"][i]["category"]["name"]
          var rating = data["category_ratings"][i]["rating"]
          var category_rating = new CategoryRating(category_name, rating);
          // debugger
          $(`#result-hook-${data["id"]}`).append(category_rating.toPage())
        }
      })

    })
  }
</script>

app/views/results/show.html.erb
<h2>Results of the <%= @result.questionnaire.name %> Questionnaire</h2>
From 4 to 20, your <%= @result.questionnaire.name %> results are:
<hr>
<% @categories.each do |category| %>
  <%= category.name %>: <%= CategoryRating.find(category.id).rating %>
  <hr>
<% end %>
Total: <%= @result.rating %> <hr>
<%= link_to "Results index", questionnaire_results_path(@result.questionnaire) %>