config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'users/new', as: 'new_user_registration'

  get 'users/create', as: 'create_new_user'

  get 'questionnaire_select/:id', to: 'questions#questionnaire_select', as: 'questionnaire_select'

  patch '/questions/:id/update_questionnaire', to: 'questions#update_questionnaire', as: 'update_questionnaire'

  delete '/questionnaires/:questionnaire_id/questions/:id', to: 'questions#destroy', as: 'destroy_question'

  post '/results/create', to: 'results#create', as: 'create_result'

  get '/questionnaires/:questionnaire_id/category/:id/show', to: 'category#show', as: 'display_category'

  patch '/questionnaires/:questionnaire_id/category/:id', to: 'category#record', as: 'record_category'

  get '/questionnaires/:questionnaire_id/results/:id/display', to: 'results#display', as: "questionnaire_result"

  get '/questionnaires/:questionnaire_id/results/:id', to: 'results#show', as: "result"

  get '/questionnaires/:questionnaire_id/category/:id/category_data', to: 'category#category_data', as: "category_data"

  resources :users

  resources :questionnaires do
    resources :questions, except: [:destroy]
    resources :results, except: [:create, :show]
  end
  post 'sessions/create_manual', as: 'create_user_session'

  get 'signout', to: 'sessions#destroy', as: 'signout'

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]

end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  belongs_to :user
  has_many :questions
  has_many :results

  validates :name, presence: true
  validates :user, presence: true
  validates :name, uniqueness: true


  def self.my_questionnaires(current_user_id)
    Questionnaire.where("user_id = #{current_user_id}")
  end

  def self.all_questionnaires(current_user_id)
    Questionnaire.where("(user_id = #{current_user_id}) or (id = 1)")
  end

  def return_questions_by_questionnaire
    Question.where("questionnaire_id = #{self.id}")
  end

  def self.default_clone
    self.first.deep_clone include: [:questions, :results]
  end

  def combine(second)
    self.name = second.name
    self.user_id = second.user_id
    self.default = second.default
    self.results.each do |result|
      second.results << result
    end
    self.questions.each do |question|
      second.questions << question
    end
    second.save
    return second
  end

  def question_attributes=(question_attributes)
    question_attributes[:body].length.times do |num|
      if question_attributes[:body]["#{num}"] != ""
        question = Question.new
        question.body = question_attributes[:body]["#{num}"]
        question.category = Category.find(question_attributes[:category_id]["#{num}"])
        question.questionnaire = self
        question.save
        self.questions << question
        self.save
      end
    end
  end

end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :require_login
  def index
    current_user_id = current_user.id
    @questionnaires = Questionnaire.my_questionnaires(current_user_id)
    respond_to do |format|
      format.json { render json: @questionnaires }
      format.html { render :index }
    end
  end

  def new
    @question_num = 0
    @questionnaire = Questionnaire.new
    @user = current_user
  end

  def edit
    @questionnaire = Questionnaire.find(params[:id])
    @user = current_user
  end

  def update
    if params[:questionnaire][:default] == "1" && params[:id] != "1"
      @questionnaire = Questionnaire.default_clone.combine(Questionnaire.find(params[:id]))
    else
      @questionnaire = Questionnaire.find(params[:id])
    end
    @questionnaire.name = params[:questionnaire][:name]
    @questionnaire.default = params[:questionnaire][:default]
    @questionnaire.user = current_user
    if !params[:questionnaire][:questions].nil?
      @questionnaire.question_attributes = params[:questionnaire][:questions]
    end
    if @questionnaire.save
      redirect_to questionnaire_path(@questionnaire)
    else
      session[:errors] = @questionnaire.errors.full_messages
      redirect_to edit_questionnaire_path(@questionnaire)
    end
  end

  def create
    if params[:questionnaire][:default] == "1"
      @questionnaire = Questionnaire.default_clone
    else
      @questionnaire = Questionnaire.new
    end
    @questionnaire.name = params[:questionnaire][:name]
    @questionnaire.default = params[:questionnaire][:default]
    @questionnaire.user = current_user
    if !params[:questionnaire][:questions].nil?
      @questionnaire.question_attributes = params[:questionnaire][:questions]
    end
    if @questionnaire.save
      redirect_to questionnaire_path(@questionnaire)
    else
      session[:errors] = @questionnaire.errors.full_messages
      redirect_to new_questionnaire_path
    end
  end

  def show
    @questionnaire = Questionnaire.find(params[:id])
    respond_to do |f|
      f.json { render json: @questionnaire, status: 201 }
      f.html { render :show }
    end

  end

  private
  def questionnaire_params
    params.require(:questionnaire).permit(:name, :default, questions_attributes: [:body, :category_id,])
  end



end

app/helpers/questionnaire_helper.rb
module QuestionnaireHelper
end

app/views/questionnaires/_form.html.erb
<% if session[:errors] %>
  <p class="alert alert-error">Ooops! Please correct the following:
    <ul>
    <% session[:errors].each do |msg| %>
        <li class="error"><%= msg %></li>
    <% end %>
    </ul>
  </p>
  <% session[:errors] = nil %>
<% end %>
<%= form_for @questionnaire do |f| %>
  <%= render 'shared/error_messages', :object => @questionnaire %>


  <%= f.label :name %>
  <%= f.text_field :name %>
  <hr>

  <%= f.label "Use Default Questions" %>
  <%= f.check_box :default %> <hr>

  <h4 id="h4-add-first">Add the First Question</h4>
  <%= f.fields_for :questions do |question| %>
    <% @question = question %>
    <div id="question_forms">
    </div>
  <% end %>
  <%= link_to "New Question", "#", id: "new_question" %>

  <hr>
  <input id="submit-questionnaire" type="submit" name="commit" value="Create Questionnaire">
<% end %>
<br><hr>

<div id="questionnaire-data">
</div>

<div id="links">
  <p id="links-paragraph" ></p>
</div>

<script type="text/javascript">
$(function() {
  $('form').submit(function(event) {
    event.preventDefault();
    $("#new_questionnaire").hide()
    var values = $(this).serialize();
    var posting = $.post('/questionnaires', values);

    posting.done(function(data) {
      $("#questionnaire-data").append("<%= j(render 'questionnaires/questionnaire_data') %>")
      $('#questionnaire-name').text(data["name"] + " Questionnaire")
      $('#questionnaire-user').text("Owned by: " + data["user"]["name"])
      $.each(data["questions"], function(index, question) {
        $('#questions').append("<h4>Question "+(index + 1)+"</h4>")
        $('#questions').append("<%= j(render 'questionnaires/question_data') %>")
        $('#question-body').attr('id', `question-body-${index}`);
        $('#question-category').attr('id', `question-body-${index}`);
        $('#question-questionnaire').attr('id', `question-body-${index}`);
        $(`#question-body-${index}`).text(question["body"])
        $(`#question-category-${index}`).text(question["category_id"])
      })
      $("#links-paragraph").append('<a href="/">Back to Main Menu</a>')

    })
  })
})
</script>


<script type="text/javascript">
  var question_num = 0;
  $("#new_question").click(function(event) {
    event.preventDefault();
    var question_form = "<%=j(render 'questionnaires/form_fields'  )%>"
    $("#question_forms").append(question_form)
    $("#questionnaire_questions_body").attr('name', `questionnaire[questions][body][${question_num}]`)
    $("#questionnaire_questions_body").attr('id', `questionnaire_questions_body_${question_num}`)
    $("#questionnaire_questions_category_id").attr('name', `questionnaire[questions][category_id][${question_num}]`)
    $("#questionnaire_questions_category_id").attr('id', `questionnaire_questions_category_id_${question_num}`)
    question_num++;
  })
</script>

app/views/questionnaires/_form_fields.html.erb
<hr>
<h4>Next Question</h4>
<div class="question_form">
  <div class="body_field">
    <label for="">Body</label><br>
    <input type="text" name="questionnaire[questions][body]" id="questionnaire_questions_body">
  </div>
  <div class="category_field">
    <label for="">Category</label><br>
    <select name="questionnaire[questions][category_id]" id="questionnaire_questions_category_id">
      <option value="1">Physical</option>
      <option value="2">Sleep</option>
      <option value="3">Mood</option>
      <option value="4">Cognition</option>
      <option value="5">Leisure</option>
      <option value="6">Social</option>
      <option value="7">Spirituality</option>
      <option value="8">Finances</option>
      <option value="9">Household</option>
      <option value="10">Self-esteem</option>
      <option value="11">Independence</option>
      <option value="12">Identity</option>
      <option value="13">Work</option>
      <option value="14">Education</option>
    </select>
  </div>
</div>

app/views/questionnaires/_question_data.html.erb
<p id="question-body"></p>
<p id="question-category"></p>
<p id="question-questionnaire"></p>
<p id="edit-link"></p>

app/views/questionnaires/_question_form.html.erb
<h4>Add a Question</h4>
<%= f.fields_for :questions do |question| %>
  <div class="field">
    <%= question.label :body %><br>
    <%= question.text_field :body %>
  </div>
  <div class="field">
    <%= question.label :category %><br>
    <%= question.collection_select :category_id, Category.all, :id, :name %><hr>
  </div>

<% end %>

app/views/questionnaires/_questionnaire_data.html.erb
<h4 id="questionnaire-name"></h4> <hr>
<h4 id="questionnaire-user"></h4>
<div id="questions">

</div>
<hr>
<p id="question-new"></p>

app/views/questionnaires/_questionnaire_show.html.erb
<h3><%= @questionnaire.name %> Questionnaire</h3> <hr>
<h4>Owned by: <%= @questionnaire.user.name %></h4>
<% if @questionnaire.questions.count == 0 %>
  <h4>No questions yet!</h4>
<% else %>
  <% @questionnaire.questions.each do |question| %>
    <p>Question: <%= question.body %></p>
    <p><strong>This question: </strong>belongs to the <strong><%= question.category.name %></strong> category</p>
    <p>and the <strong><%= @questionnaire.name %></strong> questionnaire</p>
    <%= link_to "Edit", edit_questionnaire_question_path(@questionnaire, question) %>  |  <%= link_to "Destroy", destroy_question_path(@questionnaire, question), method: :delete, data: { confirm: 'Are you sure?' } %>
    <hr>
  <% end %>
<% end %>

app/views/questionnaires/edit.html.erb
<h3>Edit Questionnaire <%= @questionnaire.name %></h3>
<%= render 'questionnaires/questionnaire_show' %>
<%= link_to "Make a new question", new_questionnaire_question_path(@questionnaire), class: "new-question" %>
<div id="question_forms"></div>
<script type="text/javascript">
  var question_num = 0;
  $(".new-question").on('click', function(event) {
    event.preventDefault();
    var question_form = "<%=j(render 'questions/form'  )%>"
    $("#question_forms").append(question_form)
    $("#questionnaire_questions_body").attr('name', `questionnaire[questions][body][${question_num}]`)
    $("#questionnaire_questions_body").attr('id', `questionnaire_questions_body_${question_num}`)
    $("#questionnaire_questions_category_id").attr('name', `questionnaire[questions][category_id][${question_num}]`)
    $("#questionnaire_questions_category_id").attr('id', `questionnaire_questions_category_id_${question_num}`)
    question_num++;
  })
</script>

app/views/questionnaires/index.html.erb
<h2>All Questionnaires</h2>

<% @questionnaires.reverse_each do |questionnaire| %>
  <%= content_tag(:p, questionnaire.name )%>
  <%= content_tag(:p, "User: #{questionnaire.user.name}" )%>
  <%= link_to "Edit", edit_questionnaire_path(questionnaire) %> | <%= link_to "Go to Questions", questionnaire_questions_path(questionnaire) %><hr>
<% end %>

app/views/questionnaires/new.html.erb
<h3>Create New Questionnaire</h3>

<%= render 'questionnaires/form' %>

app/views/questionnaires/show.html.erb
<a id="questionnaire-back" href="#">Last Questionnaire</a> | <a id="questionnaire-next" href="#">Next Questionnaire</a>
<div id="questionnaire-show"></div>
<hr>
<%= link_to "Make a new question", new_questionnaire_question_path(@questionnaire), class: "new-question" %>
<div id="question_forms"></div>
<script type="text/javascript">
  function Question(body, category, questionnaire, questionnaire_id, id) {
    this.body = body;
    this.category = category;
    this.questionnaire = questionnaire;
    this.questionnaire_id = questionnaire_id;
    this.id = id;

    this.display = function() {
      return (`
        <p>Question: ${this.body}</p>
        <p><strong>This question: </strong>belongs to the <strong>${this.category}</strong> category</p>
        <p>and the <strong>${this.questionnaire}</strong> questionnaire</p>
        <a href="/questionnaires/${this.questionnaire_id}/questions/${this.id}/edit">Edit</a> | <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/questionnaires/${this.questionnaire_id}/questions/${this.id}">Destroy</a>
      `)
    }
  }


  function load_questionnaire(q_id) {
    $.ajax({
      url: `/questionnaires/${q_id}`,
      type: 'GET'
    }).done(function(questionnaire) {
      $("#questionnaire-show").append(`<div class="questionnaire_div" id="${questionnaire["id"]}">`)
      $(".questionnaire_div").append(`<h3>${questionnaire["name"]} Questionnaire</h3> <hr>
      <h4>Owned by: ${questionnaire["user"]["name"]}</h4>`)
      if (questionnaire["questions"].length === 0) {
        $(".questionnaire_div").append("<h4>No questions yet!</h4>")
      }
      $.each(questionnaire["questions"], function(index, question) {
        var question_obj = new Question(question["body"], question["category"]["name"],
          question["questionnaire"]["name"], question["questionnaire"]["id"],
          question["id"]);
        $(".questionnaire_div").append(question_obj.display() + "<hr />")
      })
      $(".questionnaire_div").append("</div>")
    })
  }
</script>
<script type="text/javascript">
  var question_num = 0;
  $(".new-question").on('click', function(event) {
    event.preventDefault();
    var question_form = "<%=j(render 'questions/form'  )%>"
    $("#question_forms").append(question_form)
    $("#questionnaire_questions_body").attr('name', `questionnaire[questions][body][${question_num}]`)
    $("#questionnaire_questions_body").attr('id', `questionnaire_questions_body_${question_num}`)
    $("#questionnaire_questions_category_id").attr('name', `questionnaire[questions][category_id][${question_num}]`)
    $("#questionnaire_questions_category_id").attr('id', `questionnaire_questions_category_id_${question_num}`)
    question_num++;
  })
</script>

<script type="text/javascript">
  $(function() {
    var questionnaire_id = <%= @questionnaire.id %>
    load_questionnaire(questionnaire_id)
    $("#questionnaire-next").on('click', function(data) {
      var questionnaire_id = parseInt($(".questionnaire_div").attr('id'))
      $("#" + questionnaire_id).remove()
      load_questionnaire(questionnaire_id - 1);
    })
    $("#questionnaire-back").on('click', function(data) {
      var questionnaire_id = parseInt($(".questionnaire_div").attr('id'))
      $("#" + questionnaire_id).remove()
      load_questionnaire(questionnaire_id + 1);
    })
  })
</script>